#!/bin/bash
# Read the first eight chars of the UUID.
fname=${1:0:8}
# Read the task description and use it as heading for the markdown file.
description=$(task _get $1.description)
description=${description// /_}
cmd=~/.task/notes/$fname.md@$description
floaterm $cmd
# Set the indicator that the task has a note.
task $1 modify note:X
